"use client";

import { useState, type ReactNode } from "react";
import type { Confidence, ConfidenceLevel, Grade } from "@/lib/teamAnalysis/report";

// ---- Confidence badge -------------------------------------------------------

const CONF_COLOR: Record<ConfidenceLevel | "planned" | "ai", { fg: string; bg: string; bd: string }> = {
  "very-high": { fg: "#34d399", bg: "rgba(52,211,153,0.12)", bd: "rgba(52,211,153,0.40)" },
  high: { fg: "#34d399", bg: "rgba(52,211,153,0.12)", bd: "rgba(52,211,153,0.40)" },
  medium: { fg: "#fbbf24", bg: "rgba(251,191,36,0.12)", bd: "rgba(251,191,36,0.40)" },
  low: { fg: "#fb923c", bg: "rgba(251,146,60,0.12)", bd: "rgba(251,146,60,0.40)" },
  "very-low": { fg: "#fb7185", bg: "rgba(251,113,133,0.12)", bd: "rgba(251,113,133,0.40)" },
  planned: { fg: "#94a3b8", bg: "rgba(148,163,184,0.10)", bd: "rgba(148,163,184,0.35)" },
  ai: { fg: "#c084fc", bg: "rgba(192,132,252,0.12)", bd: "rgba(192,132,252,0.40)" },
};

export function ConfidenceBadge({ confidence, planned, ai }: { confidence?: Confidence; planned?: boolean; ai?: boolean }) {
  const key = ai ? "ai" : planned ? "planned" : confidence ? confidence.level : null;
  if (!key) return null;
  const c = CONF_COLOR[key];
  return (
    <span
      className="whitespace-nowrap rounded-full border px-2.5 py-0.5 text-[11px] font-semibold"
      style={{ color: c.fg, background: c.bg, borderColor: c.bd }}
      title={ai ? "Generated by Claude from the verified data" : planned ? "Arrives in a later phase" : confidence ? `${confidence.score} / 100` : undefined}
    >
      {ai ? "AI analysis" : planned ? "Planned · next phase" : confidence?.label}
    </span>
  );
}

// ---- Performance-tier badge -------------------------------------------------

const GRADE_COLOR: Record<Grade, string> = {
  S: "#f5b942",
  A: "#38bdf8",
  B: "#34d399",
  C: "#60a5fa",
  D: "#94a3b8",
  "?": "#94a3b8",
};

export function TierBadge({ grade, label }: { grade: Grade; label: string }) {
  const color = GRADE_COLOR[grade];
  return (
    <span
      className="inline-flex items-center gap-2 rounded-xl border px-3.5 py-1.5"
      style={{ color, borderColor: color, background: `${color}1a` }}
    >
      <span className="text-lg font-black leading-none">{grade}</span>
      <span className="text-xs font-bold uppercase tracking-wide">{label}</span>
    </span>
  );
}

// ---- Collapsible dropdown bar (accordion section) ---------------------------

export function Collapsible({
  index,
  title,
  confidence,
  planned,
  ai,
  open,
  onToggle,
  children,
}: {
  index: number;
  title: string;
  confidence?: Confidence;
  planned?: boolean;
  ai?: boolean;
  open: boolean;
  onToggle: () => void;
  children: ReactNode;
}) {
  return (
    <div
      className="overflow-hidden rounded-xl border transition"
      style={{ borderColor: "var(--panel-border)", background: "var(--panel)" }}
    >
      <button
        type="button"
        onClick={onToggle}
        aria-expanded={open}
        className="flex w-full items-center gap-3 px-4 py-3.5 text-left transition hover:bg-white/[0.03]"
      >
        <span className="w-5 text-sm font-bold tabular-nums text-white/35">{index}</span>
        <span className="flex-1 text-[15px] font-semibold text-white/90">{title}</span>
        {(confidence || planned || ai) && <ConfidenceBadge confidence={confidence} planned={planned} ai={ai} />}
        <span
          className="text-lg leading-none text-white/40 transition-transform duration-200"
          style={{ transform: open ? "rotate(90deg)" : "none" }}
          aria-hidden
        >
          ›
        </span>
      </button>
      {open && (
        <div className="border-t px-4 py-4 text-sm text-white/70" style={{ borderColor: "var(--panel-border)" }}>
          {children}
        </div>
      )}
    </div>
  );
}

// ---- Small building blocks --------------------------------------------------

export function StatBox({ label, value, sub }: { label: string; value: string; sub?: string }) {
  return (
    <div
      className="rounded-xl border px-4 py-3"
      style={{ borderColor: "var(--panel-border)", background: "rgba(18,28,48,0.55)" }}
    >
      <div className="text-2xl font-black tabular-nums text-white">{value}</div>
      <div className="mt-0.5 text-[11px] font-semibold uppercase tracking-wide text-white/45">{label}</div>
      {sub && <div className="text-[11px] font-medium" style={{ color: "var(--ftc-blue)" }}>{sub}</div>}
    </div>
  );
}

export function PercentBar({ label, value }: { label: string; value: number | null }) {
  return (
    <div>
      <div className="mb-1 flex items-center justify-between text-xs">
        <span className="text-white/60">{label}</span>
        <span className="tabular-nums text-white/80">{value === null ? "—" : `${value}th %ile`}</span>
      </div>
      <div className="h-2 overflow-hidden rounded-full bg-white/[0.06]">
        <div
          className="h-full rounded-full transition-[width] duration-500"
          style={{ width: `${value ?? 0}%`, background: "linear-gradient(90deg, var(--ftc-blue), #4aa3ff)" }}
        />
      </div>
    </div>
  );
}

export function ScoreBar({
  label,
  value,
  color = "var(--ftc-blue)",
  suffix = "/100",
}: {
  label: string;
  value: number;
  color?: string;
  suffix?: string;
}) {
  return (
    <div>
      <div className="mb-1 flex items-center justify-between text-xs">
        <span className="text-white/60">{label}</span>
        <span className="tabular-nums text-white/80">
          {value}
          <span className="text-white/40">{suffix}</span>
        </span>
      </div>
      <div className="h-2 overflow-hidden rounded-full bg-white/[0.06]">
        <div className="h-full rounded-full transition-[width] duration-500" style={{ width: `${Math.max(0, Math.min(100, value))}%`, background: color }} />
      </div>
    </div>
  );
}

export function KV({ k, v }: { k: string; v: string | number }) {
  return (
    <div className="flex items-baseline justify-between gap-2">
      <span className="text-white/45">{k}</span>
      <span className="tabular-nums font-medium text-white/85">{v}</span>
    </div>
  );
}

export function useAccordion(ids: string[], initiallyOpen: string[] = []) {
  const [open, setOpen] = useState<Set<string>>(new Set(initiallyOpen));
  const allOpen = ids.length > 0 && ids.every((id) => open.has(id));
  const toggle = (id: string) =>
    setOpen((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  const toggleAll = () => setOpen(allOpen ? new Set() : new Set(ids));
  return { open, allOpen, toggle, toggleAll };
}
