// Data model for a single Video Scouting session, per the phase-by-phase flow:
// Team/Alliance select -> Autonomous -> Teleop -> Endgame -> generated description.

export type Alliance = "red" | "blue";
export type StartPosition = "far" | "near";
export type BaseStatus = "none" | "partial" | "full";

export interface AutonomousStats {
  artifacts: number;
  pattern: number;
  gate: number;
  score: number; // artifacts*3 + pattern*2 (gate contributes 0)
}

export interface TeleopStats {
  artifacts: number;
  humanPlayer1: number;
  humanPlayer2: number;
  score: number; // artifacts*3 (human player actions contribute 0)
}

export interface EndgameStats {
  driverPowerPct: number; // 0-100, stored/used in description only, not scored
  baseStatus: BaseStatus;
  minorFouls: number;
  majorFouls: number;
  tacticalNotes: string;
  score: number; // baseStatus points only: none=0, partial=5, full=10
}

export interface ScoutingSession {
  teamNumber: number;
  alliance: Alliance;
  startPosition: StartPosition;
  autonomous: AutonomousStats;
  teleop: TeleopStats;
  endgame: EndgameStats;
}

export function emptyAutonomousStats(): AutonomousStats {
  return { artifacts: 0, pattern: 0, gate: 0, score: 0 };
}

export function emptyTeleopStats(): TeleopStats {
  return { artifacts: 0, humanPlayer1: 0, humanPlayer2: 0, score: 0 };
}

export function emptyEndgameStats(): EndgameStats {
  return {
    driverPowerPct: 50,
    baseStatus: "none",
    minorFouls: 0,
    majorFouls: 0,
    tacticalNotes: "",
    score: 0,
  };
}

export const BASE_STATUS_POINTS: Record<BaseStatus, number> = {
  none: 0,
  partial: 5,
  full: 10,
};

export function totalScore(session: ScoutingSession): number {
  return session.autonomous.score + session.teleop.score + session.endgame.score;
}

// The final scouting report. Numeric/raw fields (scores, driver power, tactical
// notes) are computed/copied directly from the session in code — never authored
// by the model — so they can never drift from the actual scouted data. Only the
// narrative fields are generated by Claude.
export interface ScoutingReport {
  sessionId: string;
  timestamp: string;
  savedPath: string;

  teamNumber: number;
  alliance: Alliance;
  startPosition: StartPosition;
  autonomousScore: number;
  teleopScore: number;
  endgameScore: number;
  totalScore: number;
  driverPowerPct: number;
  baseStatus: BaseStatus;
  tacticalNotes: string;

  autonomousAnalysis: string;
  teleopAnalysis: string;
  endgameAnalysis: string;
  strengths: string[];
  weaknesses: string[];
  counterStrategy: string;
  partnerStrategy: string;
  finalSummary: string;

  session: ScoutingSession;
}
